version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"               # Adjust if your .csproj is in a subfolder
    schedule:
      interval: "daily"
    registries:
      - github-packages

registries:
  github-packages:
    type: "nuget-feed"
    url: "https://nuget.pkg.github.com/akkch/index.json"
    username: "${{secrets.GITHUB_ACTOR}}"
    password: "${{secrets.CI_PAT}}"
